### PR TITLE
Added abilily to set default action to "Nothing".

### PR DESCRIPTION
**Pull request by jibbers42**
I added the ability to set default actions to "Nothing" so that you can avoid accidental drags if desired.

I hope you like it :)

### CODE REVIEW

**Comment by cyberscorpio** [comment]
Thank you!

**Comment by cyberscorpio** [comment]
I tested it and think it should be very useful.
Thank you.

BTW, are you Chinese? I think the translation (无) is very professional :)

**Comment by jibbers42** [comment]
Thank you, and thanks for writing this - it's a cool ext.

No, I'm American and only speak English; I cheated and used Google Translate :) I assume you are Chinese?? If so, your English is _very_ good.

I've never looked at FF extensions before, can you tell me how long the update process is and if you know when you plan to submit it?

**Comment by cyberscorpio** [comment]
Yes, I'm Chinese, in China, we begin to study English from 5 grade on school, but many of us never use it in work :)

I'll change the version number to 0.11 and submit it to AMO soon. If all are OK, it is expected to get approval in about 7 days.

BTW, there is a php script named 'sync-lang.php', if you have php-cli installed, you can execute it on the 'xpi' folder, it adds any new items in 'en-us/strings.dtd' and 'en-us/strings.properties' to other languages (currently zh-cn only). It is convenient if this extension supports many languages. I create it for my another extension (SuperStart), which supports 22 languages and it is a pain to add new strings without this script.

Thank you again.

**Pull request merged**
